version: "3"

services:
  cadvisor:
    restart: always
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      # Default location
      # - "/var/lib/docker/:/var/lib/docker:ro"
      # Snap location
      - "/var/snap/docker/current:/var/lib/docker:ro"
    expose:
      - "8080"
    ports:
      - 8085:8080

  prometheus:
    restart: always
    depends_on:
      - linode-exporter
    image: prom/prometheus:v2.14.0
    container_name: prometheus
    volumes:
      - "${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml"
    expose:
      - "9090"
    ports:
      - 9090:9090

  linode-exporter:
    image: dazwilkin/linode-exporter:0d20258d4df27e592e8781a58640b363499b5b1c
    container_name: linode-exporter
    command:
      - --linode_token=${LINODE_TOKEN}
    expose:
      - "2112"
    ports:
      - 2112:2112
