version: "3"

services:
  cadvisor:
    restart: always
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      # Default location
      # - "/var/lib/docker/:/var/lib/docker:ro"
      # Snap location
      - "/var/snap/docker/current:/var/lib/docker:ro"
    expose:
      - "8080"
    ports:
      - 8085:8080

  prometheus:
    restart: always
    depends_on:
      - linode-exporter
    image: docker.io/prom/prometheus:v2.42.0
    container_name: prometheus
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/rules.linode.yml:/etc/alertmanager/rules/linode.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  alertmanager:
    restart: always
    depends_on:
      - prometheus
    image: docker.io/prom/alertmanager:v0.25.0
    container_name: alertmanager
    volumes:
      - ${PWD}/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    expose:
      - "9093"
    ports:
      - 9093:9093

  linode-exporter:
    image: ghcr.io/dazwilkin/linode-exporter:${TAG}
    container_name: linode-exporter
    command:
      - --linode_token=${LINODE_TOKEN}
    expose:
      - "9388" # Linode Exporter port registered on Prometheus Wiki
    ports:
      - 9388:9388
