global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  # Self
  - job_name: "prometheus-server"
    static_configs:
      - targets:
          - "localhost:9090"

  # Linode Exporter
  - job_name: "linode-exporter"
    static_configs:
      - targets:
          - "linode-exporter:9388"

  # cAdvisor exports metrics for *all* containers running on this host
  - job_name: cadvisor
    static_configs:
      - targets:
          - "cadvisor:8080"
